In [1]:
import numpy as np

In [2]:
## in this notebook , you will find  the advance numpy functions and their use cases

## np.sort()

In [16]:
a=np.random.randint(1,100,10)
a

array([83, 52, 88, 90, 46, 97, 76,  2, 34,  2])

In [17]:
np.sort(a)

array([ 2,  2, 34, 46, 52, 76, 83, 88, 90, 97])

In [18]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[89, 10, 64, 56],
       [18, 84, 27, 16],
       [29, 11, 48, 53],
       [61, 24, 10, 20],
       [39, 58, 23, 15],
       [11, 56, 70, 68]])

In [19]:
np.sort(b,axis=0)

array([[11, 10, 10, 15],
       [18, 11, 23, 16],
       [29, 24, 27, 20],
       [39, 56, 48, 53],
       [61, 58, 64, 56],
       [89, 84, 70, 68]])

## np.append()

In [20]:
a

array([83, 52, 88, 90, 46, 97, 76,  2, 34,  2])

In [23]:
np.append(a,5)

array([83, 52, 88, 90, 46, 97, 76,  2, 34,  2,  5])

In [24]:
b

array([[89, 10, 64, 56],
       [18, 84, 27, 16],
       [29, 11, 48, 53],
       [61, 24, 10, 20],
       [39, 58, 23, 15],
       [11, 56, 70, 68]])

In [32]:
np.append(b,np.ones(4,int)).reshape(7,4)

array([[89, 10, 64, 56],
       [18, 84, 27, 16],
       [29, 11, 48, 53],
       [61, 24, 10, 20],
       [39, 58, 23, 15],
       [11, 56, 70, 68],
       [ 1,  1,  1,  1]])

In [53]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[89., 10., 64., 56.,  1.],
       [18., 84., 27., 16.,  1.],
       [29., 11., 48., 53.,  1.],
       [61., 24., 10., 20.,  1.],
       [39., 58., 23., 15.,  1.],
       [11., 56., 70., 68.,  1.]])

In [44]:
b

array([[89, 10, 64, 56],
       [18, 84, 27, 16],
       [29, 11, 48, 53],
       [61, 24, 10, 20],
       [39, 58, 23, 15],
       [11, 56, 70, 68]])

In [54]:
b

array([[89, 10, 64, 56],
       [18, 84, 27, 16],
       [29, 11, 48, 53],
       [61, 24, 10, 20],
       [39, 58, 23, 15],
       [11, 56, 70, 68]])

In [58]:
np.append(b,[[1,1,1,1]],axis=0)

array([[89, 10, 64, 56],
       [18, 84, 27, 16],
       [29, 11, 48, 53],
       [61, 24, 10, 20],
       [39, 58, 23, 15],
       [11, 56, 70, 68],
       [ 1,  1,  1,  1]])

In [59]:
b

array([[89, 10, 64, 56],
       [18, 84, 27, 16],
       [29, 11, 48, 53],
       [61, 24, 10, 20],
       [39, 58, 23, 15],
       [11, 56, 70, 68]])

In [76]:
np.append(b,np.ones((b.shape[0],1),int),axis=1)

array([[89, 10, 64, 56,  1],
       [18, 84, 27, 16,  1],
       [29, 11, 48, 53,  1],
       [61, 24, 10, 20,  1],
       [39, 58, 23, 15,  1],
       [11, 56, 70, 68,  1]])

In [77]:
np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [78]:
np.ones((b.shape[0],1)).shape

(6, 1)

In [81]:
np.ones((b.shape[1],1),int)

array([[1],
       [1],
       [1],
       [1]])

In [90]:
np.append(b,(np.ones((1,b.shape[1]),int)),axis=0)

array([[89, 10, 64, 56],
       [18, 84, 27, 16],
       [29, 11, 48, 53],
       [61, 24, 10, 20],
       [39, 58, 23, 15],
       [11, 56, 70, 68],
       [ 1,  1,  1,  1]])

In [89]:
np.ones((1,b.shape[1]),int)

array([[1, 1, 1, 1]])

## np.concatenate()

In [91]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
b=np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [98]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [99]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique()

In [100]:
e=np.array([12,2,1,12,1,12,2,12,3,45,6,78,89,54,112,12])
e

array([ 12,   2,   1,  12,   1,  12,   2,  12,   3,  45,   6,  78,  89,
        54, 112,  12])

In [101]:
np.unique(e)

array([  1,   2,   3,   6,  12,  45,  54,  78,  89, 112])

## np.expand_dims()

In [103]:
a=np.random.randint(1,100,10)
a

array([42, 18,  8, 58,  5,  6, 68, 28, 35,  1])

In [110]:
np.expand_dims(a,axis=0)

array([[42, 18,  8, 58,  5,  6, 68, 28, 35,  1]])

## np.where()

In [114]:
a

array([42, 18,  8, 58,  5,  6, 68, 28, 35,  1])

In [115]:
a[a>50]

array([58, 68])

In [121]:
np.where(a>50)

(array([3, 6], dtype=int64),)

In [125]:
np.where(a>50,0,a)

array([42, 18,  8,  0,  5,  6,  0, 28, 35,  1])

In [129]:
np.where(a%2==0,'even',a)

array(['even', 'even', 'even', 'even', '5', 'even', 'even', 'even', '35',
       '1'], dtype='<U11')

## np.argmax()

In [130]:
a

array([42, 18,  8, 58,  5,  6, 68, 28, 35,  1])

In [132]:
a[np.argmax(a)]

68

In [133]:
np.max(a)

68

In [140]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [144]:
np.argmax(b,axis=1)

array([2, 2], dtype=int64)

## np.argmin()

In [145]:
a

array([42, 18,  8, 58,  5,  6, 68, 28, 35,  1])

In [147]:
a[np.argmin(a)]

1

## np.cumsum()

In [149]:
a

array([42, 18,  8, 58,  5,  6, 68, 28, 35,  1])

In [150]:
np.cumsum(a)

array([ 42,  60,  68, 126, 131, 137, 205, 233, 268, 269])

In [151]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [154]:
np.cumsum(b,axis=0)

array([[ 6,  7,  8],
       [15, 17, 19]])

In [155]:
#Create a 5x5 matrix with row values ranging from 0 to 4

In [157]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[30, 83, 91, 71],
       [23, 14, 77, 63],
       [79, 37, 78, 92],
       [ 6, 24, 61,  5],
       [21, 19,  1, 56],
       [67, 10, 17, 17]])

In [158]:
np.cumsum(b)

array([  30,  113,  204,  275,  298,  312,  389,  452,  531,  568,  646,
        738,  744,  768,  829,  834,  855,  874,  875,  931,  998, 1008,
       1025, 1042])

In [159]:
np.cumproduct(b)

array([         30,        2490,      226590,    16087890,   370021470,
         885333284,  -548813868,  -215535316,   152579220,  1350463844,
       -2038002568,  1482324768,   304014016, -1293598208, -1600079360,
         589537792,  -504608256,  -997622272,  -997622272,   -32272384,
        2132717568,  -147660800,  1784733696,   275701760])

In [162]:
np.percentile(b,50)

33.5

## np.histogram()

In [163]:
a=np.random.randint(1,100,10)
a

array([93, 76, 37,  3,  4, 48,  6, 29, 11, 70])

In [166]:
np.histogram(a,bins=[0,10,20,30,100])

(array([3, 1, 1, 5], dtype=int64), array([  0,  10,  20,  30, 100]))

## np.corrcoef()

In [167]:
salary=np.array([120000,340500,560000,35000])
exp=np.array([5,7,9,2])


In [168]:
np.corrcoef(salary,exp)

array([[1.        , 0.95881029],
       [0.95881029, 1.        ]])

In [170]:
item=[12,2,3,3,34,1,2,37,34]
a

array([93, 76, 37,  3,  4, 48,  6, 29, 11, 70])

## np.isin()

In [173]:
a[np.isin(a,item)]

array([37,  3])

In [174]:
a

array([93, 76, 37,  3,  4, 48,  6, 29, 11, 70])

## np.flip()

In [175]:
np.flip(a)

array([70, 11, 29,  6, 48,  4,  3, 37, 76, 93])

In [176]:
a

array([93, 76, 37,  3,  4, 48,  6, 29, 11, 70])

In [177]:
a[::-1]

array([70, 11, 29,  6, 48,  4,  3, 37, 76, 93])

In [178]:
b

array([[30, 83, 91, 71],
       [23, 14, 77, 63],
       [79, 37, 78, 92],
       [ 6, 24, 61,  5],
       [21, 19,  1, 56],
       [67, 10, 17, 17]])

In [181]:
np.flip(b,axis=0)

array([[67, 10, 17, 17],
       [21, 19,  1, 56],
       [ 6, 24, 61,  5],
       [79, 37, 78, 92],
       [23, 14, 77, 63],
       [30, 83, 91, 71]])

In [182]:
a

array([93, 76, 37,  3,  4, 48,  6, 29, 11, 70])

## np.put()

In [186]:
np.put(a,(0,1),(11,45))

In [187]:
a

array([11, 45, 37,  3,  4, 48,  6, 29, 11, 70])

In [188]:
a

array([11, 45, 37,  3,  4, 48,  6, 29, 11, 70])

## np.delete()

In [189]:
a

array([11, 45, 37,  3,  4, 48,  6, 29, 11, 70])

In [190]:
np.delete(a,(0,1,2))


array([ 3,  4, 48,  6, 29, 11, 70])

In [191]:
a

array([11, 45, 37,  3,  4, 48,  6, 29, 11, 70])

## set functions

In [193]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])


In [194]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7])

In [195]:
np.intersect1d(a,b)

array([3, 4, 5])

In [197]:
np.setdiff1d(b,a)

array([6, 7])

In [198]:
np.setxor1d(a,b)

array([1, 2, 6, 7])

In [201]:
a[np.in1d(a,b)]

array([3, 4, 5])

## np.clip()

In [202]:
a

array([1, 2, 3, 4, 5])

In [203]:
b

array([3, 4, 5, 6, 7])

In [204]:
np.clip(a,2,5)

array([2, 2, 3, 4, 5])

In [206]:
a=np.random.randint(1,100,50)
a

array([57, 31, 57, 69, 95, 59, 88,  8, 99, 72, 70, 94, 94, 99, 84, 49, 37,
       95, 56, 64, 10,  7, 74, 47,  2, 16, 83,  7, 65, 49, 54, 97, 72, 97,
       17, 77, 27, 16,  4, 80, 72, 22, 56, 62, 24, 78, 94, 84, 37, 35])

In [207]:
np.clip(a,20,70)

array([57, 31, 57, 69, 70, 59, 70, 20, 70, 70, 70, 70, 70, 70, 70, 49, 37,
       70, 56, 64, 20, 20, 70, 47, 20, 20, 70, 20, 65, 49, 54, 70, 70, 70,
       20, 70, 27, 20, 20, 70, 70, 22, 56, 62, 24, 70, 70, 70, 37, 35])