In [1]:
import numpy as np

In [3]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
b=np.ones((3,3))*3
b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [21]:
c=np.empty(2)
c   ## it will give you any random value 

array([9.95696155e-296, 2.38126870e+022])

In [20]:
d=np.empty(2)
d

array([9.95696155e-296, 2.38126870e+022])

In [25]:
e=np.ones((3,4),dtype=int)
e

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
np.eye(5).reshape(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
import pandas as pd


In [32]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
pd.DataFrame(a)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [36]:
import random

In [47]:
random.choice((1,2,3,4,5,6))

6

In [55]:
random.choice("vaish")

'h'

In [61]:
random.randrange(1,10)

5

In [64]:
random.random()

0.7808293202494071

In [68]:
l=[1,2,3,4,5,6]


In [72]:
random.shuffle(l)
l

[3, 2, 5, 4, 1, 6]

In [106]:
random.uniform(1,10)

8.37182410633677

In [84]:
random.random() ## generate a random number between 0 and 1 


0.7065127005063624

In [113]:
np.random.rand(2,3).reshape(3,2)

array([[0.7915    , 0.61910561],
       [0.0025444 , 0.79271958],
       [0.38211215, 0.08560572]])

In [117]:
np.random.rand(1)

array([0.39967076])

In [120]:
np.random.randn(2,3)

array([[ 0.91252868,  1.69906872,  0.04061532],
       [ 2.23328157, -0.07674697, -0.39510824]])

In [123]:
np.random.random_sample((2,3))

array([[0.55474038, 0.21991529, 0.30399941],
       [0.07602076, 0.9942464 , 0.88432356]])

In [133]:
m=np.random.randint(1,10,size=(2,5))
m

array([[6, 8, 2, 9, 3],
       [3, 4, 8, 3, 8]])

In [134]:
m.size

10

In [135]:
m.shape

(2, 5)

In [136]:
m.dtype

dtype('int32')

In [137]:
m.ndim

2

In [144]:
n=np.random.randn(1,10).reshape(5,2)
n

array([[ 0.23879269,  0.05657357],
       [ 0.45026766, -0.00321163],
       [ 0.26600998,  0.82275308],
       [ 0.23906579, -0.33670433],
       [ 0.2566194 ,  0.98634253]])

In [145]:
n.reshape(10,1)

array([[ 0.23879269],
       [ 0.05657357],
       [ 0.45026766],
       [-0.00321163],
       [ 0.26600998],
       [ 0.82275308],
       [ 0.23906579],
       [-0.33670433],
       [ 0.2566194 ],
       [ 0.98634253]])

In [148]:
n.reshape(10,-100)

array([[ 0.23879269],
       [ 0.05657357],
       [ 0.45026766],
       [-0.00321163],
       [ 0.26600998],
       [ 0.82275308],
       [ 0.23906579],
       [-0.33670433],
       [ 0.2566194 ],
       [ 0.98634253]])

In [149]:
n.reshape(-90,10)

array([[ 0.23879269,  0.05657357,  0.45026766, -0.00321163,  0.26600998,
         0.82275308,  0.23906579, -0.33670433,  0.2566194 ,  0.98634253]])

In [160]:
n.reshape(10,-1)

array([[ 3.        ],
       [ 0.05657357],
       [ 0.45026766],
       [-0.00321163],
       [ 0.26600998],
       [ 0.82275308],
       [ 0.23906579],
       [-0.33670433],
       [ 0.2566194 ],
       [ 0.98634253]])

In [159]:
n[0][0]=3.0000
n

array([[ 3.        ,  0.05657357],
       [ 0.45026766, -0.00321163],
       [ 0.26600998,  0.82275308],
       [ 0.23906579, -0.33670433],
       [ 0.2566194 ,  0.98634253]])

In [166]:
n.reshape(5,2)

array([[ 3.        ,  0.05657357],
       [ 0.45026766, -0.00321163],
       [ 0.26600998,  0.82275308],
       [ 0.23906579, -0.33670433],
       [ 0.2566194 ,  0.98634253]])

In [168]:
k=np.random.randn(1,10)
k

array([[ 1.06855511, -0.24558841, -0.18644255, -0.69224989,  1.73399562,
        -1.01922974,  0.51448711, -2.25311415, -0.26450375, -2.12239901]])

In [170]:
k.reshape(5,2).base

array([[ 1.06855511, -0.24558841, -0.18644255, -0.69224989,  1.73399562,
        -1.01922974,  0.51448711, -2.25311415, -0.26450375, -2.12239901]])

In [172]:
k

array([[ 1.06855511, -0.24558841, -0.18644255, -0.69224989,  1.73399562,
        -1.01922974,  0.51448711, -2.25311415, -0.26450375, -2.12239901]])

In [173]:
k.reshape(2,5)

array([[ 1.06855511, -0.24558841, -0.18644255, -0.69224989,  1.73399562],
       [-1.01922974,  0.51448711, -2.25311415, -0.26450375, -2.12239901]])

In [187]:
f=np.random.randint(1,10,12).reshape(1,1,1,2,3,2)
f

array([[[[[[1, 7],
           [2, 8],
           [8, 2]],

          [[9, 4],
           [1, 9],
           [7, 9]]]]]])

In [188]:
l=[1,2,3,4]
l

[1, 2, 3, 4]

In [189]:
np.array(l)

array([1, 2, 3, 4])

In [192]:
m=np.array([[1,2],[3,4]])

In [193]:
m.ndim

2

In [197]:
arr2=np.zeros((3,4))

In [198]:
arr2.ndim

2

In [202]:
arr3=np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [203]:
arr4=np.zeros((1,3,4)) ## 3rows +4 columns >> 1 2d array+ 1d 
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [205]:
arr4.ndim

3

In [207]:
arr5=np.zeros((1,1,3,4))  # 3rows+ 4cols>> 2d array+ 1D
arr5

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [208]:
arr5.ndim

4

In [218]:
arr1=np.random.randint(1,10,(5,6))
arr1

array([[5, 8, 3, 2, 3, 3],
       [1, 6, 3, 5, 9, 2],
       [2, 6, 3, 1, 7, 4],
       [5, 6, 3, 2, 7, 2],
       [9, 1, 2, 8, 1, 1]])

In [220]:
arr1[arr1>5].reshape(3,3)

array([[8, 6, 9],
       [6, 7, 6],
       [7, 9, 8]])

In [221]:
arr1

array([[5, 8, 3, 2, 3, 3],
       [1, 6, 3, 5, 9, 2],
       [2, 6, 3, 1, 7, 4],
       [5, 6, 3, 2, 7, 2],
       [9, 1, 2, 8, 1, 1]])

In [226]:
arr1[1::][2::]

array([[5, 6, 3, 2, 7, 2],
       [9, 1, 2, 8, 1, 1]])

In [231]:
arr1

array([[5, 8, 3, 2, 3, 3],
       [1, 6, 3, 5, 9, 2],
       [2, 6, 3, 1, 7, 4],
       [5, 6, 3, 2, 7, 2],
       [9, 1, 2, 8, 1, 1]])

In [230]:
arr1[0:3,0:5]

array([[5, 8, 3, 2, 3],
       [1, 6, 3, 5, 9],
       [2, 6, 3, 1, 7]])

In [233]:
arr1[1:3,1:4]

array([[6, 3, 5],
       [6, 3, 1]])

In [235]:
arr1[1:3,[1,4]]

array([[6, 9],
       [6, 7]])

In [236]:
arr1

array([[5, 8, 3, 2, 3, 3],
       [1, 6, 3, 5, 9, 2],
       [2, 6, 3, 1, 7, 4],
       [5, 6, 3, 2, 7, 2],
       [9, 1, 2, 8, 1, 1]])

In [240]:
arr1[2:5,[1,3,5]]

array([[6, 1, 4],
       [6, 2, 2],
       [1, 8, 1]])

In [249]:
arr1[[2,4],0:3]

array([[2, 6, 3],
       [9, 1, 2]])

In [254]:
arr1[::,[2,4]]

array([[3, 3],
       [3, 9],
       [3, 7],
       [3, 7],
       [2, 1]])

In [267]:
arr3=np.random.randint(1,5,(3,3))
arr3

array([[1, 1, 2],
       [3, 1, 4],
       [1, 4, 4]])

In [268]:
arr4=np.random.randint(1,5,(3,3))
arr4

array([[3, 4, 1],
       [1, 1, 4],
       [2, 3, 3]])

In [269]:
arr3+arr4

array([[4, 5, 3],
       [4, 2, 8],
       [3, 7, 7]])

In [270]:
arr3*arr4

array([[ 3,  4,  2],
       [ 3,  1, 16],
       [ 2, 12, 12]])

In [271]:
m1=np.matrix(arr3)
m1

matrix([[1, 1, 2],
        [3, 1, 4],
        [1, 4, 4]])

In [272]:
m2=np.matrix(arr4)
m2

matrix([[3, 4, 1],
        [1, 1, 4],
        [2, 3, 3]])

In [274]:
m1*m2

matrix([[ 8, 11, 11],
        [18, 25, 19],
        [15, 20, 29]])

In [276]:
m1@m2

matrix([[ 8, 11, 11],
        [18, 25, 19],
        [15, 20, 29]])

In [278]:
arr3

array([[1, 1, 2],
       [3, 1, 4],
       [1, 4, 4]])

In [279]:
arr4

array([[3, 4, 1],
       [1, 1, 4],
       [2, 3, 3]])

In [284]:
(arr4/arr3)

array([[3.        , 4.        , 0.5       ],
       [0.33333333, 1.        , 1.        ],
       [2.        , 0.75      , 0.75      ]])

In [285]:
5/0

ZeroDivisionError: division by zero

In [286]:
arr3

array([[1, 1, 2],
       [3, 1, 4],
       [1, 4, 4]])

In [287]:
arr3/0

C:\Users\Vaishnavi\AppData\Local\Temp\ipykernel_7524\1466893960.py:1: RuntimeWarning: divide by zero encountered in divide
  arr3/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [289]:
y=np.ones((5,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [290]:
y+1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [298]:
z=np.array([1,2,3,4,5])
z

array([1, 2, 3, 4, 5])

In [299]:
y+z

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [300]:
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [303]:
z1=np.array([1,2,3,4,5])
z1

array([1, 2, 3, 4, 5])

In [304]:
z1

array([1, 2, 3, 4, 5])

In [308]:
y+z1

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [309]:
z1.transpose()

array([1, 2, 3, 4, 5])

In [310]:
y+z1

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [312]:
q=np.ones((3,4))
q

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [313]:
r=np.array([1,2,3,4])
r

array([1, 2, 3, 4])

In [314]:
q+r

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [322]:
r1=np.array([[1,2,3]])
r1

array([[1, 2, 3]])

In [323]:
q+r1

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [324]:
r1.T

array([[1],
       [2],
       [3]])

In [327]:
q+r1.T

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [328]:
a=np.random.randint(1,5,size=(3,4))
a

array([[4, 2, 2, 3],
       [3, 3, 4, 3],
       [3, 3, 1, 3]])

In [334]:
b=np.random.randint(1,5,(4,1))
b

array([[2],
       [1],
       [2],
       [3]])

In [336]:
a+b.T

array([[6, 3, 4, 6],
       [5, 4, 6, 6],
       [5, 4, 3, 6]])

In [338]:
np.sqrt(a)

array([[2.        , 1.41421356, 1.41421356, 1.73205081],
       [1.73205081, 1.73205081, 2.        , 1.73205081],
       [1.73205081, 1.73205081, 1.        , 1.73205081]])

In [339]:
np.log10(m1)

matrix([[0.        , 0.        , 0.30103   ],
        [0.47712125, 0.        , 0.60205999],
        [0.        , 0.60205999, 0.60205999]])

In [340]:
np.exp(a)

array([[54.59815003,  7.3890561 ,  7.3890561 , 20.08553692],
       [20.08553692, 20.08553692, 54.59815003, 20.08553692],
       [20.08553692, 20.08553692,  2.71828183, 20.08553692]])

In [341]:
np.mean(m1)

2.3333333333333335

In [342]:
m1

matrix([[1, 1, 2],
        [3, 1, 4],
        [1, 4, 4]])

In [343]:
np.min(m1)

1

In [344]:
np.max(m1)

4

In [347]:
np.complex64(m1)

matrix([[1.+0.j, 1.+0.j, 2.+0.j],
        [3.+0.j, 1.+0.j, 4.+0.j],
        [1.+0.j, 4.+0.j, 4.+0.j]], dtype=complex64)

In [348]:
arr1

array([[5, 8, 3, 2, 3, 3],
       [1, 6, 3, 5, 9, 2],
       [2, 6, 3, 1, 7, 4],
       [5, 6, 3, 2, 7, 2],
       [9, 1, 2, 8, 1, 1]])

In [350]:
arr1.flatten()

array([5, 8, 3, 2, 3, 3, 1, 6, 3, 5, 9, 2, 2, 6, 3, 1, 7, 4, 5, 6, 3, 2,
       7, 2, 9, 1, 2, 8, 1, 1])

In [351]:
#expand_dims

In [352]:
a

array([[4, 2, 2, 3],
       [3, 3, 4, 3],
       [3, 3, 1, 3]])

In [353]:
sum(a)

array([10,  8,  7,  9])

In [354]:
np.sum(a)

34

In [355]:
np.sum(a,axis=1)

array([11, 13, 10])

In [356]:
np.sum(a,axis=0)

array([10,  8,  7,  9])

In [357]:
np.sum(a,axis=1)

array([11, 13, 10])

In [360]:
arr1=np.array([1,2,3,4])
arr2=np.expand_dims(arr1,axis=1)
arr2

array([[1],
       [2],
       [3],
       [4]])

In [362]:
arr3=np.expand_dims(arr1,axis=0)
arr3

array([[1, 2, 3, 4]])

In [363]:
arr4=np.expand_dims(arr3,axis=0)
arr4

array([[[1, 2, 3, 4]]])