In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [3]:
np.squeeze(a)

array([1, 2, 3, 4])

In [6]:
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [7]:
np.squeeze(a1)

array([1, 2, 3, 4])

In [9]:
np.repeat(a,2).reshape(4,2)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [11]:
a

array([1, 2, 3, 4])

In [12]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [14]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [18]:
np.roll([1,2,3],shift=4)

array([3, 1, 2])

In [20]:
np.diag(np.array([1,2,3,4,5,6,7,8,9,10,2]))

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2]])

In [21]:
np.roll([1,2,3],-1)

array([2, 3, 1])

In [25]:
np.diag_indices(1,2)

(array([0]), array([0]))

## binary operations

In [27]:
arr1=np.random.randint(1,10,size=(3,4))
arr1

array([[8, 1, 2, 7],
       [8, 1, 6, 3],
       [4, 8, 6, 6]])

In [29]:
arr2=np.random.randint(1,10,size=(3,4))
arr2

array([[3, 9, 6, 3],
       [6, 8, 3, 4],
       [4, 9, 4, 6]])

In [30]:
arr1+arr2

array([[11, 10,  8, 10],
       [14,  9,  9,  7],
       [ 8, 17, 10, 12]])

In [31]:
arr1*arr2

array([[24,  9, 12, 21],
       [48,  8, 18, 12],
       [16, 72, 24, 36]])

In [32]:
arr1**arr2

array([[      512,         1,        64,       343],
       [   262144,         1,       216,        81],
       [      256, 134217728,      1296,     46656]])

In [37]:
arr1[arr1>arr2]

array([8, 7, 8, 6, 6])

In [34]:
~arr1

array([[-9, -2, -3, -8],
       [-9, -2, -7, -4],
       [-5, -9, -7, -7]])

## numpy string functions

In [41]:
s1=np.array(['    pw','skills'])
s1

array(['    pw', 'skills'], dtype='<U6')

In [42]:
np.char.upper(s1)

array(['    PW', 'SKILLS'], dtype='<U6')

In [43]:
np.char.lstrip(s1)

array(['pw', 'skills'], dtype='<U6')

In [44]:
np.char.capitalize(s1)

array(['    pw', 'Skills'], dtype='<U6')

In [45]:
np.char.title(s1)

array(['    Pw', 'Skills'], dtype='<U6')

# mathematical functions

In [47]:
np.sin(np.array([[1,2],[3,4]]))

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [49]:
np.cos(np.array([1,2,3,4]))

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [53]:
np.std(np.array([1,2,-90,1000]))

447.1332994756709

In [54]:
arr1

array([[8, 1, 2, 7],
       [8, 1, 6, 3],
       [4, 8, 6, 6]])

In [55]:
np.count_nonzero(arr1)

12

In [56]:
a=np.array([1,2,3,3,0,1])
a

array([1, 2, 3, 3, 0, 1])

In [58]:
np.count_nonzero(a)


5

In [61]:
np.extract(a>0,a)

array([1, 2, 3, 3, 1])

In [69]:
arr1=np.array([1,2,3,2,4])
np.searchsorted(np.array([1,2,3,2,4]),2)

1

## linear equations 

In [73]:
arr1=np.random.randint(1,10,(3,4))
arr1

array([[5, 6, 6, 6],
       [8, 2, 4, 4],
       [5, 2, 2, 6]])

In [76]:
arr2=np.random.randint(1,10,(4,3))
arr2

array([[4, 9, 5],
       [3, 2, 6],
       [4, 9, 2],
       [7, 4, 2]])

In [77]:
arr1@arr2

array([[104, 135,  85],
       [ 82, 128,  68],
       [ 76,  91,  53]])

In [78]:
a=np.array([[7,5,-3],[2,-5,2],[5,3,-7]])
a

array([[ 7,  5, -3],
       [ 2, -5,  2],
       [ 5,  3, -7]])

In [79]:
b=np.array([16,-8,0])
b

array([16, -8,  0])

In [85]:
np.linalg.solve(a,b)

array([1.11304348, 2.85217391, 2.0173913 ])

In [82]:
np.little_endian

True

In [89]:
np.linalg.det(a)

230.00000000000006